### PR TITLE
Implemented solving method calls on ArrayAccessExpr and SuperExpr.

### PR DESCRIPTION
**Pull request by mlangkabel**
This fixes issue #41.

### CODE REVIEW

**Comment by mlangkabel** [comment]
Maybe we should wait merging this branch. Let me try to write tests first :)

**Comment by ftomassetti** [comment]
It is really good to see more tests :D
Thank you for all your amazing work!

**Comment by mlangkabel** [comment]
No problem! I guess there will be coming many more updates in the future. Right now I'm trying to minimize the amout of exceptions when indexing the whole Javaparser project :)

**Comment by ftomassetti** [comment]
Perfect, and at some point we should think about releasing a new version

**Comment by mlangkabel** [comment]
Would you like to update the symbol solver to use Javaparser 3.0 first?

**Comment by ftomassetti** [comment]
Yes

**Comment by mlangkabel** [comment]
That's nice to hear!

**Comment by matozoid** [comment]
3.0 won't be out for at least a few months!

**Comment by ftomassetti** [comment]
maybe we should move to JavaParser 3.0.0.alpha2 then

**Comment by mlangkabel** [comment]
I think that's a good idea, so we won't have to do the full spread of adjustments once the release of JavaParser 3.0 hits.

**Comment by matozoid** [comment]
Alright, but don't expect more than -SNAPSHOT quality from it.

**Pull request merged**
