### PR TITLE
walkmod changes

### PR DESCRIPTION
**Pull request by rpau**
Hi Federico,

With your code I have detected 3 bugs on my "compiler" side. Two of them has been solved easily and the last version of the compiler has been deployed to the Maven Central repository. The first two bugs were:

1) Multiple imports that import a simple class name (some by wildcard an another explicitly).
2) Access to inherited attributes whose type is a TypeParameter (T) from "this".

The third bug is related to the type inference mechanism introduced in Java 8 (https://docs.oracle.com/javase/tutorial/java/generics/genTypeInference.html), when for example if you have a class like this one:

    public class A { public static void processAList(List<A> stringList) {}}

And you apply this call: 
A.processAList(Collections.emptyList());

The compiler must infer that emptyList() returns a List<A>. However, if I rewrite the expression in Java 7 like this one:

A.processAList(Collections.<A>emptyList());

The compiler works. I have needed to apply this little change in me.tomassetti.symbolsolver.model.declarations.ClassDeclaration. Line: 53

I am going create an issue for it: https://github.com/rpau/javalang-compiler/issues/2

For another hand, I have detected 2 issues into the clean code plugin that can be improved. I am going to add it as an issue:
https://github.com/rpau/walkmod-dead-code-cleaner-plugin/issues/1

### CODE REVIEW

**Comment by ftomassetti** [comment]
I took your configuration, made a few adaptions and prepared PR #2 which I am going to merge (if all tests pass). Thanks a lot!

**Comment by rpau** [comment]
Federico, I have seen that you preserve the walkmod.xml in your project. It would be nice that you subscribe your project in the walkmodhub. I will do it for my projects too ASAP. It will process the following pushes into the project just for the modified files and gives you an sticker of "clean code" for the project like travis does :)

**Comment by ftomassetti** [comment]
done and sticker added :)
It says that I have a PR pending but I cannot see it, it is marked as PR -1 (I can send you a screenshot if you need it)

**Comment by rpau** [comment]
Hi,

You have received a code clean sticker :)
Yes, if the system says (-1) send me the screenshot. I am not in the office now, but I will take a look tomorrow.

**Comment by ftomassetti** [comment]
Screenshot send, I just hope I had the right e-mail, if you do not get it
let me know

On Thu, Aug 27, 2015 at 6:22 PM, Raquel Pau <notifications@github.com>
wrote:

> Hi,
>
> You have received a code clean sticker :)
> Yes, if the system says (-1) send me the screenshot. I am not in the
> office now, but I will take a look tomorrow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ftomassetti/java-symbol-solver/pull/1#issuecomment-135483641>
> .
>



-- 
Website at http://tomassetti.me <http://www.federico-tomassetti.it>
GitHub https://github.com/ftomassetti

**Pull request closed without merging**
